name: Build

on:
  push:
    branches:
      - main
    paths:
      - '**/*.js'
      - '**/*.jsx'
      - '**/src/**'
      - 'next.config.mjs'
      - 'package-*.json'

jobs:
  Build:
    runs-on: ubuntu-latest
    name: Build
    env:
      NEXT_TELEMETRY_DISABLED: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
        env:
          DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
